### ISSUE TITLE
[CORS ISSUE ON EDGE BROWSER] Pokemons are displayed instead of Twitter Avatars

### ISSUE THREAD

**Issue by ashishk1331** [sankalp1999/twitter-circle#11]
![image](https://github.com/sankalp1999/twitter-circle/assets/44055846/af6cc72f-08a6-42c1-afcf-b8c065e923f0)

### Problems,
1. The Twitter circle should display Twitter avatars but Pokemon avatars are being displayed.
2. The circle is copped off vertically when the number of users increases. [Visible in the above image]

### Steps to recreate,
I followed the steps mentioned in the README.
1. cloned the repo
2. placed twitter-archive folder
3. installed dependencies
4. ran setup.sh
5. hit run!

### Possible assumptions,
I've used `git bash` to run the `sh` script on my `Windows` machine. Maybe the script didn't work supposedly. A Windows' issue?

**Comment by sankalp1999** [comment]
Thanks a lot Ashish for dropping on the call. There is basically CORS issue for Edge browser. I will debug and fix it.
It works on chrome. Will keep this issue open for sometime.
