### ISSUE TITLE
failed execution of ./setup.sh in second run.

### ISSUE THREAD

**Issue by anuragts** [sankalp1999/twitter-circle#8]
So if running ./setup.sh doesn't work in first time (my case), so running the setup.sh script fails to run, as a package.lock.json is created and in the script it pulls the changes and you cannot pull without committing changes.

![image](https://github.com/sankalp1999/twitter-circle/assets/79055093/580251b7-8afc-4733-83b7-640553686ba1)

**Comment by sankalp1999** [comment]
I think you might have made some uncommited code changes hence the unstaged changes error.
first time users will have it up to date. I just checked `git pull` after `git clone` works fine. regarding people who are making changes, I think they can manage themselves (like doing git stash etc.)

**Comment by anuragts** [comment]
No, so when I ran setup.sh first time it didn't worked correctly due to some unforeseen error in the process it generates a package.lock.json, so I ran setup.sh second time there it failed.

This can also help in testing as don't need to stash changes again & again by yourself.

But yeah people manage this themselves.

**Comment by sankalp1999** [comment]
Ok I get your logic now.
